theme = "catppuccin_mocha"

[editor]
scrolloff = 10
default-yank-register = '"'
line-number = "relative"
cursorline = true
cursorcolumn = false
rulers = [81, 101]
bufferline = "multiple"
color-modes = true
text-width = 100
trim-trailing-whitespace = true
end-of-line-diagnostics = "hint"
editor-config = true

[editor.statusline]
center = ["version-control"]

[editor.lsp]
display-inlay-hints = true
inlay-hints-length-limit = 20

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = false

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[editor.smart-tab]
supersede-menu = true

[editor.inline-diagnostics]
cursor-line = "info"
other-lines = "error"

[keys.normal]
"ret" = ["open_below", "normal_mode"]
"S-ret" = ["open_above", "normal_mode"]

[keys.insert]
Meta-space = "no_op"
