theme = "catppuccin_mocha"

[editor]
line-number = "relative"
rulers = [81, 101]
text-width = 90
trim-trailing-whitespace = true
end-of-line-diagnostics = "hint"

[editor.lsp]
display-inlay-hints = true

[editor.file-picker]
hidden = true

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[keys.insert]
Meta-space = "no_op"

[editor.inline-diagnostics]
cursor-line = "warning"
